version: "3.9"

services:
  app:
    build: .
    image: synthomat/myuri:0.11
    ports:
      - "4000:3000"
    environment:
      DATABASE_URL: jdbc:postgresql://db/myuri?user=myuri&password=CHANGE_ME_TOO
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: myuri
      POSTGRES_PASSWORD: CHANGE_ME_TOO
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
