version: "3.9"

services:
  app:
    image: synthomat/myuri:0.6
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: jdbc:postgresql://db/myuri?user=myuri&password=CHANGEME_CHANGEME_PLEASE
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: myuri
      POSTGRES_PASSWORD: CHANGEME_CHANGEME_TOO
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
