version: "3.9"

services:
  app:
    image: synthomat/myuri:0.5
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: jdbc:postgresql://db/myuri?user=myuri&password=8c2677a2726089ff9782b38647ee169a7ae920b9
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: myuri
      POSTGRES_PASSWORD: 8c2677a2726089ff9782b38647ee169a7ae920b9
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: