name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/')
    if: false == false

    steps:
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1113 # Clojure CLI based on tools.deps

          # (optional) To avoid rate limit errors please provide github token
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build artifact
        run: clojure -T:build uber

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.jar